options:
  conda-extra-packages:
    type: string
    default: ""
    description: |
      Space separated list of extra packages to `conda install`
  conda-extra-pip-packages:
    type: string
    default: ""
    description: |
      Space separated list of extra packages to `pip install` into the conda env
  conda-installer-url:
    type: string
    default: "https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh"
    description: |
      URL to install conda from
  conda-installer-checksum:
    type: string
    default: "866ae9dff53ad0874e1d1a60b1ad1ef8"
    description: |
      SHA checksum for installer
  conda-installer-hash-type:
    type: string
    default: "md5"
    description: |
      Hash type to use for conda checksum
  python-version:
    type: string
    default: "3.6"
    description: |
      Python version to use in the conda env
